# Explicitly declare this is a v2 configuration
version: 2

# Before hooks for setup tasks
before:
  hooks:
    - go mod tidy

# Build configuration for the CLI
builds:
  - id: spinup-cli
    binary: spinup
    main: ./cmd/spinup-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

# Release settings
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  mode: replace

# Checksum generation
checksum:
  name_template: 'checksums.txt'

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew formula configuration updated for v2
brews:
  - name: spinup
    description: Simple command-line interface for spinup
    homepage: https://github.com/YaleSpinup/spinup-cli
    license: AGPL-3.0-or-later
    repository:
      owner: yalespinup
      name: homebrew-tools
      branch: main
      # In v2, the folder path is specified in the tap section
      path: Formula
    install: |
      bin.install "spinup"
    test: |
      system "#{bin}/spinup", "version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com