# Required version declaration for GoReleaser v2
version: 2

# Pre-build hooks remain the same
before:
  hooks:
    - go mod tidy

# Build configuration for the CLI
builds:
  - id: spinup-cli
    binary: spinup
    main: ./cmd/spinup-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

# Release settings with explicit mode
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  mode: replace

# Checksum configuration
checksum:
  name_template: 'checksums.txt'

# Changelog settings
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew formula configuration following v2 structure
brews:
  - name: spinup
    description: Simple command-line interface for spinup
    homepage: https://github.com/YaleSpinup/spinup-cli
    license: AGPL-3.0-or-later
    # Repository configuration is now more detailed
    repository:
      owner: yalespinup
      name: homebrew-tools
      branch: main
    # Formula directory specification
    directory: Formula
    # Installation script
    install: |
      bin.install "spinup"
    # Test script
    test: |
      system "#{bin}/spinup", "version"
    # Commit configuration
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com